version: '3.8'

services:
  datamend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datamend-dev
    ports:
      - "8501:8501"
    environment:
      # Development environment settings
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_ENABLE_CORS=true
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - STREAMLIT_LOGGER_LEVEL=debug
      
      # Load from .env file
      - LLM_PROVIDER=${LLM_PROVIDER}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_MODEL=${LLM_MODEL}
      
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_USERNAME=${SNOWFLAKE_USERNAME}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
      
      - ORACLE_CONNECTION_STRING=${ORACLE_CONNECTION_STRING}
      - ORACLE_USERNAME=${ORACLE_USERNAME}
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      
      - HDFS_NAMENODE_URL=${HDFS_NAMENODE_URL}
      - HDFS_USERNAME=${HDFS_USERNAME}
      - HDFS_TIMEOUT=${HDFS_TIMEOUT}
    volumes:
      # Mount source code for development
      - .:/app
      # Separate volume for data
      - ./data:/app/data
      # Mount local wallet for Oracle
      - ./wallet:/app/wallet:ro
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    networks:
      - datamend-dev

  # Optional: Development database services
  postgres-dev:
    image: postgres:15-alpine
    container_name: datamend-postgres-dev
    environment:
      - POSTGRES_DB=datamend
      - POSTGRES_USER=datamend
      - POSTGRES_PASSWORD=dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - datamend-dev

volumes:
  postgres_dev_data:

networks:
  datamend-dev:
    driver: bridge
