version: '3.8'

services:
  datamend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datamend-prod
    ports:
      - "80:8501"
    environment:
      # Production environment settings
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=true
      
      # LLM Configuration
      - LLM_PROVIDER=${LLM_PROVIDER}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_MODEL=${LLM_MODEL}
      
      # Database configurations from environment
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_USERNAME=${SNOWFLAKE_USERNAME}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
      
      - ORACLE_CONNECTION_STRING=${ORACLE_CONNECTION_STRING}
      - ORACLE_USERNAME=${ORACLE_USERNAME}
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      
      - HDFS_NAMENODE_URL=${HDFS_NAMENODE_URL}
      - HDFS_USERNAME=${HDFS_USERNAME}
      - HDFS_TIMEOUT=${HDFS_TIMEOUT}
    volumes:
      # Production data mount
      - /opt/datamend/data:/app/data:ro
      # Production logs
      - /opt/datamend/logs:/app/logs
      # Oracle wallet for production
      - /opt/datamend/wallet:/app/wallet:ro
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      - datamend-prod

  # Optional: Reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: datamend-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/ssl/private:/etc/ssl/private:ro
    depends_on:
      - datamend
    restart: always
    networks:
      - datamend-prod

networks:
  datamend-prod:
    driver: bridge
